        if (_now > round_[_rID].end && round_[_rID].ended == false && round_[_rID].plyr != 0)
        if (_now > round_[_rID].strt + rndGap_ && (_now <= round_[_rID].end || (_now > round_[_rID].end && round_[_rID].plyr == 0)))
 if (_now < round_[_rID].end)
            if (_now > round_[_rID].strt + rndGap_)
        if (now > round_[_rID].end && round_[_rID].ended == false && round_[_rID].plyr != 0)
        if (_now > round_[_rID].strt + rndGap_ && (_now <= round_[_rID].end || (_now > round_[_rID].end && round_[_rID].plyr == 0))) 
            if (_now > round_[_rID].end && round_[_rID].ended == false) 
        } else if (_now > round_[_rID].end && round_[_rID].ended == false) {
        if (_now > round_[_rID].strt + rndGap_ && (_now <= round_[_rID].end || (_now > round_[_rID].end && round_[_rID].plyr == 0)))
        if (_now > round_[_rID].strt + rndGap_ && (_now <= round_[_rID].end || (_now > round_[_rID].end && round_[_rID].plyr == 0)))
        if (_now > round_[_rID].end && round_[_rID].plyr == 0)
        if (_newTime < (rndMax_).add(_now))
        if((seed - ((seed / 1000) * 1000)) < airDropTracker_)
