        if (_now > round[_rID].end && round[_rID].ended == false && round[_rID].plyr != 0)
        if (_now > round[_rID].strt + rndGap_ && (_now <= round[_rID].end || (_now > round[_rID].end && round[_rID].plyr == 0)))
  if (_now < round[_rID].end)
            if (_now > round[_rID].strt + rndGap_)
        if (now > round[_rID].end && round[_rID].ended == false && round[_rID].plyr != 0)
        if (_now > round[_rID].strt + rndGap_ && (_now <= round[_rID].end || (_now > round[_rID].end && round[_rID].plyr == 0))) 
            if (_now > round[_rID].end && round[_rID].ended == false) 
        if (_now > round[_rID].strt + rndGap_ && (_now <= round[_rID].end || (_now > round[_rID].end && round[_rID].plyr == 0))) 
        } else if (_now > round[_rID].end && round[_rID].ended == false) {
        if (_now > round[_rID].strt + rndGap_ && (_now <= round[_rID].end || (_now > round[_rID].end && round[_rID].plyr == 0)))
        if (_now > round[_rID].strt + rndGap_ && (_now <= round[_rID].end || (_now > round[_rID].end && round[_rID].plyr == 0)))
        if (_now > round[_rID].end && round[_rID].plyr == 0)
        if (_newTime < (rndMax_).add(_now))
        if((seed - ((seed / 1000) * 1000)) < airDropTracker_)
