        if (_now > round_[_rID].end && round_[_rID].ended == false)
        if (_now > round_[_rID].strt + rndGap_ && round_[_rID].eth != 0 && _now <= round_[_rID].end)
        else if (_now <= round_[_rID].end) // round hasn't ended (in ICO phase, or ICO phase is over, but round eth is 0)
        if (_now <= round_[_rID].strt + rndGap_)
            if (_now < round_[_rID].end)
        if (now > round_[_rID].end && round_[_rID].ended == false)
        if (now <= round_[rID_].strt + rndGap_) 
        if (now <= round_[rID_].strt + rndGap_) 
            if (now > round_[_rIDlast].strt + rndGap_ && round_[_rIDlast].eth == 0)
        else if (_now <= round_[_rID].end) // round hasn't ended (in ICO phase, or ICO phase is over, but round eth is 0)
        if (_now > round_[_rID].strt + rndGap_ && round_[_rID].eth != 0 && _now <= round_[_rID].end)
        else if (_now <= round_[_rID].end) // round hasn't ended (in ICO phase, or ICO phase is over, but round eth is 0)
        if (_now > round_[_rID].end)
        if (_newTime < (rndMax_).add(_now))
        if((seed - ((seed / 1000) * 1000)) < airDropTracker_)
