        if (_now > round_.end && round_.ended == false && round_.plyr != 0)
        if (_now > round_.strt + rndGap_ && (_now <= round_.end || (_now > round_.end && round_.plyr == 0)))
  if (_now < round_.end)
            if (_now > round_.strt + rndGap_)
        if (now > round_.end && round_.ended == false && round_.plyr != 0)
        if (_now > round_.strt + rndGap_ && (_now <= round_.end || (_now > round_.end && round_.plyr == 0))) 
        if (_now > round_.strt + rndGap_ && (_now <= round_.end || (_now > round_.end && round_.plyr == 0))) 
        } else if (_now > round_.end && round_.ended == false) {
                if (round_.plyr != _pID)
        if (_now > round_.strt + rndGap_ && (_now <= round_.end || (_now > round_.end && round_.plyr == 0)))
        if (_now > round_.strt + rndGap_ && (_now <= round_.end || (_now > round_.end && round_.plyr == 0)))
        if (_dust > 0)
        if (_earnings > 0)
        if (_now > round_.end && round_.plyr == 0)
        if (_newTime < (rndMax_).add(_now))
        if (_dust > 0)
